In [5]:
!CFLAGS="-stdlib=libc++" pip install fairseq

  Using cached fairseq-0.9.0.tar.gz (306 kB)
  Using cached regex-2020.2.20.tar.gz (681 kB)
  Using cached sacrebleu-1.4.4-py3-none-any.whl (30 kB)
  Using cached portalocker-1.5.2-py2.py3-none-any.whl (14 kB)
  Using cached typing-3.7.4.1-py3-none-any.whl (25 kB)
  Created wheel for fairseq: filename=fairseq-0.9.0-cp36-cp36m-macosx_10_9_x86_64.whl size=633378 sha256=bcab80aaebea9220f528ada9bee2e98c0410cd1a8bcf166b514548cecb5873fa
  Stored in directory: /Users/kakao/Library/Caches/pip/wheels/fb/85/9b/286072121774d5b8b0253ab66271b558069189cbe795bc6084
  Created wheel for regex: filename=regex-2020.2.20-cp36-cp36m-macosx_10_9_x86_64.whl size=303889 sha256=9abcab3e633340e6f6ea27adee1ec0ba8853ad064cadd8df894000e071412c44
  Stored in directory: /Users/kakao/Library/Caches/pip/wheels/87/cd/81/c7cd4e15b481ffb1c95e1107bd3674ebad20bca9ef4581ae2f
Successfully built fairseq regex


In [6]:
import torch
from fairseq.models.wav2vec import Wav2VecModel

In [11]:
import IPython.display as ipd
import librosa

In [43]:
cp=torch.load('../datasets/wav2vec_large.pt', map_location=torch.device('cpu'))
model = Wav2VecModel.build_model(cp['args'], task=None)
model.load_state_dict(cp['model'])
model.eval()

Wav2VecModel(
  (feature_extractor): ConvFeatureExtractionModel(
    (conv_layers): ModuleList(
      (0): Sequential(
        (0): Conv1d(1, 512, kernel_size=(10,), stride=(5,), bias=False)
        (1): Dropout(p=0.0, inplace=False)
        (2): Fp32GroupNorm(1, 512, eps=1e-05, affine=True)
        (3): ReLU()
      )
      (1): Sequential(
        (0): Conv1d(512, 512, kernel_size=(8,), stride=(4,), bias=False)
        (1): Dropout(p=0.0, inplace=False)
        (2): Fp32GroupNorm(1, 512, eps=1e-05, affine=True)
        (3): ReLU()
      )
      (2): Sequential(
        (0): Conv1d(512, 512, kernel_size=(4,), stride=(2,), bias=False)
        (1): Dropout(p=0.0, inplace=False)
        (2): Fp32GroupNorm(1, 512, eps=1e-05, affine=True)
        (3): ReLU()
      )
      (3): Sequential(
        (0): Conv1d(512, 512, kernel_size=(4,), stride=(2,), bias=False)
        (1): Dropout(p=0.0, inplace=False)
        (2): Fp32GroupNorm(1, 512, eps=1e-05, affine=True)
        (3): ReLU()
      )
 

Wav2VecModel(
  (feature_extractor): ConvFeatureExtractionModel(
    (conv_layers): ModuleList(
      (0): Sequential(
        (0): Conv1d(1, 512, kernel_size=(10,), stride=(5,), bias=False)
        (1): Dropout(p=0.0, inplace=False)
        (2): Fp32GroupNorm(1, 512, eps=1e-05, affine=True)
        (3): ReLU()
      )
      (1): Sequential(
        (0): Conv1d(512, 512, kernel_size=(8,), stride=(4,), bias=False)
        (1): Dropout(p=0.0, inplace=False)
        (2): Fp32GroupNorm(1, 512, eps=1e-05, affine=True)
        (3): ReLU()
      )
      (2): Sequential(
        (0): Conv1d(512, 512, kernel_size=(4,), stride=(2,), bias=False)
        (1): Dropout(p=0.0, inplace=False)
        (2): Fp32GroupNorm(1, 512, eps=1e-05, affine=True)
        (3): ReLU()
      )
      (3): Sequential(
        (0): Conv1d(512, 512, kernel_size=(4,), stride=(2,), bias=False)
        (1): Dropout(p=0.0, inplace=False)
        (2): Fp32GroupNorm(1, 512, eps=1e-05, affine=True)
        (3): ReLU()
      )
 

In [44]:
file_path = "../datasets/IEMOCAP_CUTTED" + '/Ses01F_impro01_F000.wav'
data, sr = librosa.load(file_path)

In [19]:
import numpy as np

In [46]:
data=np.expand_dims(data, axis=0)

In [47]:
data

array([[-0.00070661, -0.00308682, -0.00480553, ..., -0.00380395,
        -0.00218341,  0.        ]], dtype=float32)

In [48]:
wav_input_16khz=torch.tensor(data)

In [49]:
wav_input_16khz

tensor([[-0.0007, -0.0031, -0.0048,  ..., -0.0038, -0.0022,  0.0000]])

In [50]:
z = model.feature_extractor(wav_input_16khz)
c = model.feature_aggregator(z)

In [51]:
c.shape

torch.Size([1, 512, 266])

In [52]:
z.shape

torch.Size([1, 512, 266])

In [53]:
z

tensor([[[0.0000, 0.0000, 0.0000,  ..., 0.0135, 0.0051, 0.0049],
         [0.0506, 0.0000, 0.0000,  ..., 0.0337, 0.0415, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         ...,
         [0.0000, 0.0118, 0.0115,  ..., 0.0000, 0.0000, 0.0129],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0463, 0.0508, 0.0663,  ..., 0.0624, 0.0734, 0.0593]]],
       grad_fn=<LogBackward>)